name: Compile & Check

on:
  push:
    branches: ["main", "russian", "russian-dev"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: # Manual trigger added
  workflow_call: # Allow other Actions to call this workflow

jobs:
  Compile-and-Check:
    runs-on: windows-latest
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v7

    - name: Compile and syntax check with Windows PowerShell 5.1
      shell: powershell
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        ./Compile.ps1
      continue-on-error: false

    - name: Compile and syntax check with PowerShell 7
      shell: pwsh
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        ./Compile.ps1
      continue-on-error: false
